#!/usr/bin/env bash
# Build the relay locally, ship it to the droplet, and bring it up behind Caddy.
# Idempotent: safe to re-run for every deployment.
set -euo pipefail

HOST="${RELAY_HOST:-root@206.189.135.109}"
REMOTE_DIR=/opt/sih-relay
CADDY_FRAGMENT=/etc/caddy/sites/sih-api.caddy
HERE="$(cd "$(dirname "$0")" && pwd)"

# The relay's /publish endpoint is the gateway's identity. Newest-publisher-wins
# means an unauthenticated /publish is not a smaller feature set, it is a
# takeover: anyone can impersonate the gateway, inject fabricated snapshots and
# alarms, and read every subscriber's command traffic.
#
# This used to be handed to compose as "${RELAY_PUBLISH_SECRET:-}", interpolated
# from the environment of a NON-INTERACTIVE ssh shell - which is empty. No .env
# was ever shipped, so the live relay logged "publish secret NOT set" and served
# an open publish endpoint on the public internet. Require it here, and ship it
# as a file the remote compose actually reads.
if [ -z "${RELAY_PUBLISH_SECRET:-}" ]; then
  cat >&2 <<'MSG'
RELAY_PUBLISH_SECRET is not set in THIS shell.

The relay refuses to serve an unauthenticated /publish endpoint on a public
address, so deploying without it would produce a crash-looping container.

  export RELAY_PUBLISH_SECRET="$(openssl rand -hex 32)"
  export RELAY_WRITE_TOKEN="$(openssl rand -hex 32)"   # optional; gates ack/close
  ./deploy/deploy-relay.sh

Put the same value in server/config.js's relay.publishSecret source
(RELAY_PUBLISH_SECRET in the gateway's environment). See deploy/.env.example.
MSG
  exit 1
fi

# Tracks whether the fragment has been copied onto the droplet, and whether
# Caddy has successfully reloaded with it. If we exit for any reason with the
# fragment installed but not yet reloaded, the trap below removes it - the
# live Caddyfile does `import /etc/caddy/sites/*.caddy`, so a stray bad
# fragment left on disk is a landmine for the next restart of the caddy
# service (reboot, unattended-upgrades, an unrelated deploy), even though the
# currently-running Caddy process is unaffected.
FRAGMENT_INSTALLED=0
RELOADED=0
LOCAL_ENV_FILE=""

cleanup() {
  # The generated env file holds the publish secret in cleartext. It never
  # outlives the run that created it.
  [ -n "$LOCAL_ENV_FILE" ] && rm -f "$LOCAL_ENV_FILE"
  if [ "$FRAGMENT_INSTALLED" = "1" ] && [ "$RELOADED" != "1" ]; then
    echo "==> cleanup: removing un-activated caddy fragment from droplet"
    ssh "$HOST" "rm -f $CADDY_FRAGMENT" || true
  fi
}
trap cleanup EXIT ERR

echo "==> building image for linux/amd64"
# The droplet is amd64 and a developer Mac is arm64. Without --platform the
# image builds for the wrong architecture and fails at runtime with a confusing
# 'exec format error'.
docker build --platform linux/amd64 -t sih-relay:latest "$HERE/../relay"

echo "==> shipping image"
docker save sih-relay:latest | gzip | ssh "$HOST" 'gunzip | docker load'

echo "==> shipping compose file"
ssh "$HOST" "mkdir -p $REMOTE_DIR"
scp "$HERE/docker-compose.yml" "$HOST:$REMOTE_DIR/docker-compose.yml"

echo "==> shipping secrets"
# `docker compose` reads $REMOTE_DIR/.env from its project directory, which is
# where the ${VAR} interpolation in docker-compose.yml gets its values. Written
# 0600 locally BEFORE anything is put in it, so the secret is never briefly
# world-readable on either machine.
LOCAL_ENV_FILE="$(mktemp)"
chmod 600 "$LOCAL_ENV_FILE"
{
  echo "# Generated by deploy/deploy-relay.sh. Do not edit by hand."
  echo "RELAY_PUBLISH_SECRET=$RELAY_PUBLISH_SECRET"
  if [ -n "${RELAY_WRITE_TOKEN:-}" ]; then
    echo "RELAY_WRITE_TOKEN=$RELAY_WRITE_TOKEN"
  else
    echo "RELAY_WRITE_TOKEN="
  fi
} > "$LOCAL_ENV_FILE"
ssh "$HOST" "install -m 600 /dev/null $REMOTE_DIR/.env"
scp "$LOCAL_ENV_FILE" "$HOST:$REMOTE_DIR/.env"
ssh "$HOST" "chmod 600 $REMOTE_DIR/.env"

echo "==> starting container"
ssh "$HOST" "cd $REMOTE_DIR && docker compose up -d --force-recreate"

echo "==> waiting for backend readiness"
# Nothing touches Caddy until the container answers on its own. Without this,
# a crash-looping container would still get exposed publicly the moment we
# reload, because the only backend check used to happen AFTER the reload.
ssh "$HOST" '
  for i in $(seq 1 20); do
    if curl -sf http://127.0.0.1:3040/health >/dev/null 2>&1; then
      exit 0
    fi
    sleep 1
  done
  echo "relay backend never became healthy on 127.0.0.1:3040" >&2
  exit 1
'

echo "==> shipping caddy config"
scp "$HERE/sih-api.caddy" "$HOST:$CADDY_FRAGMENT"
FRAGMENT_INSTALLED=1

echo "==> validating caddy BEFORE reload"
# Five production sites share this proxy. A bad fragment must be caught here,
# not by discovering the whole box stopped serving - and it must not survive
# on disk for some future restart to trip over.
if ! ssh "$HOST" 'caddy validate --config /etc/caddy/Caddyfile --adapter caddyfile >/dev/null 2>&1'; then
  echo "caddy config INVALID - removing fragment and aborting"
  ssh "$HOST" "rm -f $CADDY_FRAGMENT"
  exit 1
fi

ssh "$HOST" 'systemctl reload caddy'
RELOADED=1

echo "==> verifying"
sleep 3
ssh "$HOST" 'curl -sf http://127.0.0.1:3040/health' && echo
curl -sf https://api.sih.shubhang.dev/health && echo

echo "==> verifying the publish endpoint is actually gated"
# The failure this whole script exists to prevent is silent, so assert it
# rather than trusting that the env file arrived.
if ssh "$HOST" "docker logs sih-relay 2>&1 | tail -50 | grep -q 'publish secret NOT set'"; then
  echo "FATAL: the relay came up with an OPEN /publish endpoint." >&2
  exit 1
fi
ssh "$HOST" "docker logs sih-relay 2>&1 | tail -5"
echo "==> deployed"
