"""Export the real MC-120 Blender meshes to PRAVAAH's offline scene renderer.

Run with Blender --background assets/MiningConveyor.blend --python tools/export-mining-model.py.
Bevel modifiers are omitted for a compact browser mesh; plate thickness is retained.
The source .blend is never modified. Native animation is translated to distance-based
metadata, so the dashboard's measured speed, pause and freshness controls own time.
"""
import bpy, json, math, os, hashlib, re
from pathlib import Path
from mathutils import Vector

ROOT = Path(__file__).resolve().parents[1]
scene = bpy.context.scene
scene.frame_set(1)
for o in scene.objects:
    for m in o.modifiers:
        if m.type == 'BEVEL': m.show_viewport = False
bpy.context.view_layer.update()
depsgraph = bpy.context.evaluated_depsgraph_get()

def monitoring(o):
    n=o.name
    if n.startswith('ORE'): return 'material_flow'
    if n.startswith('BELT'): return 'belt_carcass' if 'carcass' in n else 'belt_tracking'
    if n.startswith(('DRUM','SHAFT')): return 'tail_pulley' if 'TAIL' in n else 'drive_pulley'
    if n.startswith('BEARING') or ('bearing foot' in n): return 'tail_bearing' if 'TAIL' in n else 'drive_bearing'
    if n.startswith('TAKE-UP'): return 'takeup'
    if n.startswith('IDLER'):
        if 'Return' in n: return 'return_idlers'
        return 'idlers' if re.search(r'04(?:\.|$)',n) else 'carry_idlers'
    if n.startswith('MOTOR'): return 'drive_motor'
    if n.startswith(('GEARBOX','COUPLING')) or n.startswith('DRIVE | Input'): return 'gearbox'
    if n.startswith('HOPPER') or 'Skirt' in n: return 'loading_chute'
    if n.startswith('CHUTE'): return 'discharge_chute'
    if n.startswith('BIN'): return 'receiving_bin'
    if n.startswith('CLEANER'): return 'head_scraper'
    if n.startswith(('WALKWAY','LADDER')) or 'Handrail' in n or 'handrail' in n or 'toe plate' in n: return 'walkway'
    if n.startswith('GUARD | Belt') or n.startswith('GUARD | Guide'): return 'training_idler'
    if n.startswith('CONTROL') or 'Emergency stop' in n: return 'local_controls'
    return 'structural_frame'

def motion(o):
    root=o
    while root.parent:root=root.parent
    n=root.name
    if 'Travel_m' in root:
        return {'kind':'belt','offset':root['Travel_m']},root
    if 'Cycle_m' in root:
        expr=next(f.driver.expression for f in root.animation_data.drivers if f.data_path=='location' and f.array_index==2)
        return {'kind':'ore','offset':root['Cycle_m'],'lane':root.location.y,'height':float(re.match(r'[0-9.]+',expr)[0])},root
    if root.animation_data:
        for f in root.animation_data.drivers:
            if f.data_path=='rotation_euler':
                rate=8/.55 if f.array_index==0 else -1/.135 if 'Return' in n else 1/.165 if 'Carry' in n else 1/.55
                return {'kind':'spin','pivot':list(root.location),'axis':f.array_index,'rate':rate},root
    return None,root

def color(material):
    def srgb(x):return 12.92*x if x<=.0031308 else 1.055*x**(1/2.4)-.055
    return '#'+''.join(f'{max(0,min(255,round(srgb(v)*255))):02x}' for v in material.diffuse_color[:3])

parts=[]
for o in sorted(scene.objects,key=lambda x:x.name):
    if o.type not in {'MESH','FONT'} or any(c.name.startswith('90 ') for c in o.users_collection):continue
    ev=o.evaluated_get(depsgraph);me=ev.to_mesh()
    if not me or not me.polygons:continue
    anim,root=motion(o)
    transform=o.matrix_world
    if anim and anim['kind']=='belt':transform=root.matrix_world.inverted()@o.matrix_world
    vertices=[]
    for v in me.vertices:
        p=transform@v.co
        if anim and anim['kind']=='ore':p-=root.location
        vertices.append([round(float(x),5) for x in p])
    mat=o.data.materials[0] if o.data.materials else None
    name=mat.name if mat else ''
    material='rubber' if 'Belt' in name else 'coal' if 'Ore' in name else 'steel' if any(x in name for x in ['steel','Machined']) else 'paint'
    part={'id':f'part:{len(parts):03d}','name':o.name,'assembly':o.users_collection[0].name,
          'component':monitoring(o),'color':color(mat) if mat else '#9badbd','material':material,
          'vertices':vertices,'faces':[list(p.vertices) for p in me.polygons]}
    if anim:part['motion']=anim
    parts.append(part);ev.to_mesh_clear()

data={'name':'MC-120','source':'MiningConveyor.blend','sha256':hashlib.sha256(Path(bpy.data.filepath).read_bytes()).hexdigest(),
      'units':'metres','axis':'Blender Z up','belt':{'x0':-5,'x1':5,'radius':.55,'height':2.2,'width':1.65,'loopLength':20+2*math.pi*.55},
      'parts':parts}
out=ROOT/'web'/'assets'/'mining-conveyor.js';out.parent.mkdir(parents=True,exist_ok=True)
out.write_text('// Generated by tools/export-mining-model.py from the actual Blender asset.\nexport default '+json.dumps(data,separators=(',',':'))+';\n',encoding='utf-8')
print('EXPORTED',len(parts),'parts',sum(len(p['faces']) for p in parts),'faces',out.stat().st_size,'bytes',flush=True)
